#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name: /var/tmp/tomcat/sell.log
#  level:
#    root: info

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.154/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null # 全局配置：不返回null的对象
server:
  servlet:
    context-path: /sell/
